Make code style consistent
SpineEventEngine/embed-code pull request #34
Opened 2024-04-22 14:55 UTC by vb-td

In this PR the code style was formatted to be consistent. 

All the error messages are started from the lower case and don't have period at the end. 

The disclaimers were provided for all code files.

Tests were rewritten in a more compact way, with the support of `testify` package. All test messages were formatted in the same style as well. All tests are now united into "suites", which is the workflow that `testify` recommends. With suites, it is now possible to define setup and teardown functions for all tests.  All helper functions were replaced into a separated package. 

### Other changes:
* the actions for building the app were added. Now, with every PR to `embed-code-go` branch, the building is executed, and resulting binaries for Windows, MacOS and Ubuntu are placed into the `./bin` directory;
* the `README.md` was filled with the all necessary information about running, installation and compilation. Also, the information about setting up code and documentation files was taken from the original `README.md`.

2024-04-24 17:36 UTC, armiol commented
@vb-td no PR can be simultaneously in its draft state, and ready for review.

2024-04-24 17:36 UTC, armiol commented
@vb-td 
> All the error messages are started from the lower case and doesn't have period at the end.

Let's fix the grammar issues.

2024-04-25 09:07 UTC, dmytro-kashcheiev requested changes
@vb-td LGTM in general but see comments.

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on .github/workflows/ubuntu_go.yml
> +          go test -v ./... -p 1
Lets document. Or use full version of `-p` flag if any. Now it's unclear why before it was ok without this flag, and now it was added.

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on .github/workflows/win_go.yml
Please verify if still need this, or we can replace it with a matrix and have one action? One action is much easier to maintain.

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on .gitignore
> -embed-code-go/build
Are we sure about this? Doesn't this mean that local builds now result in changed files in the git?

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on embed-code-go/README.md
> +1. Embedding - in this mode, all documentation files are scanned for `<embed-code>` tags, and the corresponding embeddings are performed.
Where do embeding results go? To some build folder or just replace the content of original files with the `<embed-code>` tag? We should specify this.

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on embed-code-go/README.md
> +2. Checking for up-to-date - in this mode, all documentation files are checked for being up-to-date. If the check fails, an error message with the corresponding files is provided.
After addressing above comment you can specify what files are checked against `new-version`, since up-to-date means that `something` is aware of latest update `somewhere` we should specify what is compared here.

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on embed-code-go/README.md
> +To compile the file, Go must have been [installed](#installation) first.
`must have been installed` sounds too complicated can we say `ensure Go installed ../`

2024-04-25 09:07 UTC, dmytro-kashcheiev commented on embed-code-go/test/utils/io.go
I propose to avoid `utils`. Even though there is just one file such folders always result in hundreds of files from all over the world. Rethink naming here to be more specific. 

For example (just example): 
`io/directories.go` -> force next developers to have only IO files here, and only directory-related functions in script;
`filesystem/io.go` -> force next developers to have only file system-related files here;
`testfixture/io.go` -> similar to `utils` but at list, we specify that we want only testing related utilities here; 
....

2024-04-25 11:42 UTC, armiol requested changes
@vb-td see my comments in addition to those left by Dmitry.

2024-04-25 11:42 UTC, armiol commented on embed-code-go/README.md
> +2. Checking for up-to-date - in this mode, all documentation files are checked for being up-to-date. If the check fails, an error message with the corresponding files is provided.
In English that would be "Checking for the latest version" or "Checking for being up-to-date".

2024-04-25 11:42 UTC, armiol commented on embed-code-go/README.md
> +The tool can be executed as a binary file or as a Go file. In the latter case, the user must have Go [installed](#installation). The development version is `1.22.1`. The binary files are stored in th
Please make the version more visible. It deserves its own section.

Maybe, a good idea would be just to provide a reference to some file, which is a real source of truth.

2024-04-25 11:42 UTC, armiol commented on embed-code-go/README.md
> +
This line is redundant.

2024-04-25 12:39 UTC, vb-td commented on .gitignore
> -embed-code-go/build
Ok, I've returned it. Firstly I wanted to use this dir for builds, but then I changed my mind 😅

2024-04-25 13:11 UTC, vb-td commented on embed-code-go/README.md
> +The tool can be executed as a binary file or as a Go file. In the latter case, the user must have Go [installed](#installation). The development version is `1.22.1`. The binary files are stored in th
Done!

2024-04-26 12:28 UTC, armiol approved these changes
@vb-td LGTM from my side.

I would also suggest to have some automated tests against real binaries that we build, in scope of respective OS-es. E.g., after we run Go tests and assembly a binary under, say, macOS, we should use this binary in a number of "integration" tests to verify the binary is ready for use.

2024-04-26 13:01 UTC, dmytro-kashcheiev approved these changes
@vb-td LGTM with minor comment

2024-04-26 13:01 UTC, dmytro-kashcheiev commented on .github/workflows/go_tests.yml
> +          go test -v ./... -p 1
Lets fix this EOF.

2024-04-26 15:24 UTC, merged