Refactor `fragmentation` package
SpineEventEngine/embed-code pull request #51
Opened 2024-09-13 14:02 UTC by olena-zmiiova

The code was rearranged, and the remained issues from the linter were fixed. Also added UTs using `ginkgo` and `gomega` libs.

> Note: There is a failing test, converting PR to draft until debugged.

2024-09-13 17:14 UTC, armiol commented
@olena-zmiiova JFYI, I have removed the quotation markdown symbol (`>`) and put an emoji to the PR description, because what you had was not a quote.

2024-09-17 14:26 UTC, dmytro-kashcheiev requested changes
@olena-zmiiova see comments.

2024-09-17 14:26 UTC, dmytro-kashcheiev commented on embed-code-go/analyzing/analyzing.go
>  		fmt.Sprintf("%s/%s", analyticsDir, embeddingChangedFile), changedEmbeddings)
`fmt.Sprintf(...)` can be extracted to a variable with a name to make `WriteLinesToFile ` more transparent, same below.

2024-09-17 14:26 UTC, dmytro-kashcheiev commented on embed-code-go/files/files.go
> +func ReadFile(path string) ([]string, error) {
`(path)` here doesn't consistent with `filepath string ` above.

2024-09-17 14:26 UTC, dmytro-kashcheiev commented on embed-code-go/files/files.go
> +func WriteLinesToFile(filepath string, lines []string) {
Since there is `BuildDocRelativePath`  I propose to mention in the docs that both file types are supported by this function, same for other funcs in this file.

2024-09-17 14:26 UTC, dmytro-kashcheiev commented on embed-code-go/fragmentation/partition.go
> +func (p Partition) Select(lines []string) []string {
Not sure about `Go` but in most of other languages it's better to check array boundaries for such methods to have some meaningful exception in case there are no such indexes in the array.

2024-09-17 14:26 UTC, dmytro-kashcheiev commented on embed-code-go/fragmentation/fragmentation.go
> +func (f Fragmentation) parseDocFragments(docFragments []string, cursor int) error {
According to `parseEndDocFragments ` func and related doc this func should be named as `parseStartDocFragments `

2024-09-17 16:49 UTC, olena-zmiiova commented on embed-code-go/files/files.go
> +func WriteLinesToFile(filepath string, lines []string) {
> both file types are supported by this function

You mean that functions support relative and absolute file paths, correct?

2024-09-18 08:46 UTC, dmytro-kashcheiev commented on embed-code-go/files/files.go
> +func WriteLinesToFile(filepath string, lines []string) {
@olena-zmiiova yes

2024-09-18 08:54 UTC, dmytro-kashcheiev approved these changes
@olena-zmiiova LGTM

2024-09-18 10:25 UTC, merged